### PR TITLE
Upgrade Cake to 0.17.0

### PR DESCRIPTION
**Pull request by devlead**
Cake 0.18.0 will requires at least version 0.16.x to work.

There was a failing unit test too...made it pass but unsure if it's correct so please review. 😉

### CODE REVIEW

**Comment by MihaMarkic** [comment]
I'll merge it. Out of the curiosity, is this requirement documented somewhere? Since I have other add ins.

**Comment by devlead** [comment]
It'll be, 0.18.0 isn't released yet, but  each release will have minimum version specified.

**Comment by MihaMarkic** [comment]
OK, checked the bug you fixed. It turns out that the test is wrong. Can you revert that and perhaps update the unit test (or leave it to me) so I can merge the update to 0.17?

**Comment by devlead** [comment]
I'll can revert that, ping back here when done.

**Comment by devlead** [comment]
Reverted, all compiles and all test but the mentioned one pass
image

**Pull request merged**
